apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/reikamoon/kargo-tutorial-test.git
    targetRevision: main
    path: guestbook-apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd