apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-simple-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-simple
  namespace: guestbook-simple-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-simple
  template:
    metadata:
      labels:
        app: guestbook-simple
    spec:
      containers:
      - image: ghcr.io/reikamoon/guestbook:v0.0.1
        name: guestbook-simple
        ports:
        - containerPort: 3000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-simple
  namespace: guestbook-simple-dev
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: guestbook-simple
