apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      steps:
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-01-prod
            sources:
            - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
              updateTargetRevision: true
  verification:
    analysisTemplates:
    - name: kargo-demo