apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: ${GITOPS_REPO_URL}
          checkout:
          - branch: main
            path: ./src
          - branch: stage/dev
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/base
          images:
          - image: public.ecr.aws/nginx/nginx
      - uses: kustomize-build
        config:
          path: ./src/stages/dev
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/dev
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-dev
            sources:
            - repoURL: ${GITOPS_REPO_URL}
              desiredCommitFromStep: commit

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: ${GITOPS_REPO_URL}
          checkout:
          - branch: main
            path: ./src
          - branch: stage/test
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/base
          images:
          - image: ghcr.io/reikamoon/guestbook
      - uses: kustomize-build
        config:
          path: ./src/stages/test
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/test
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-test
            sources:
            - repoURL: ${GITOPS_REPO_URL}
              desiredCommitFromStep: commit

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: ${GITOPS_REPO_URL}
          checkout:
          - branch: main
            path: ./src
          - branch: stage/uat
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/base
          images:
          - image: ghcr.io/reikamoon/guestbook
      - uses: kustomize-build
        config:
          path: ./src/stages/uat
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/uat
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-uat
            sources:
            - repoURL: ${GITOPS_REPO_URL}
              desiredCommitFromStep: commit

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: ${GITOPS_REPO_URL}
          checkout:
          - branch: main
            path: ./src
          - branch: stage/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/base
          images:
          - image: ghcr.io/reikamoon/guestbook
      - uses: kustomize-build
        config:
          path: ./src/stages/prod
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/prod
      - uses: git-open-pr
        config:
          repoURL: ${GITOPS_REPO_URL}
          sourceBranch: main
          targetBranch: stage/prod
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-prod
            sources:
            - repoURL: ${GITOPS_REPO_URL}
              desiredCommitFromStep: commit
