apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:test
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                - {key: akuity.io/argo-cd-cluster-name, operator: NotIn, values: [in-cluster]}
          - list:
              elements:
              - env: test
              - env: staging
              - env: prod
  template:
    metadata:
      name: 'guestbook-simple-{{env}}'
      annotations:
        "kargo.akuity.io/authorized-stage:guestbook-simple:{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/reikamoon/kargo-tutorial-test
        targetRevision: main
        path: 'app/env/{{env}}'
      destination:
        name: '{{name}}'
        namespace: 'guestbook-simple-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
